package com.eraandroid.core.lexer

enum class TokenType {
    // Literals
    INTEGER, FLOAT, STRING, IDENTIFIER,

    // Keywords
    IF, ELSEIF, ELSE, ENDIF,
    FOR, TO, NEXT,
    WHILE, WEND,
    DO, LOOP, UNTIL,
    REPEAT, REND,
    CALL, CALLFORM, TRYCALLFORM, FUNC, ENDFUNC,
    RETURN, RETURNF, GOTO, GOSUB,
    PRINT, PRINTL, PRINTW, PRINTD, PRINTFORM, PRINTFORML,
    PRINTV, PRINTVL, PRINTS, PRINTSL,
    PRINTC_CMD, PRINTLC_CMD, PRINTFORMC_CMD, PRINTFORMLC_CMD,
    INPUT, INPUTMOUSEKEY, TINPUT, TWAIT, WAIT,
    BEGIN, CALLTRAIN,
    SET_COLOR, RESET_COLOR, SET_BG_COLOR, RESET_BG_COLOR,
    BUTTON, SELECTCASE, CASE, CASEELSE, ENDSELECT,
    VARSET, CVARSET, ARRAYSHIFT, ARRAYREMOVE,
    RANDOMIZE, LIMIT, SQRT, ABS, SIGN, MAX, MIN, INRANGE,
    STRJOIN, SPLIT, STRLENS, SUBSTRING, CHARATU, STRFIND,
    TOINT, TOSTR, ISNUMERIC,
    GETTIME, GETMILLISECOND,
    SAVEDATA, LOADDATA, DELDATA, CHKDATA,
    PRINTBUTTON, PRINTBUTTONC, PRINTBUTTONLC,
    SAVEGLOBAL, LOADGLOBAL,
    THROW, TRYSELECTCASE, TRYCALL, TRYFUNC,
    DEBUGPRINT, ASSERT, SIF,
    NOP, QUIT, RESET_STAIN,
    ADDCHARA, DELCHARA, SWAPCHARA, SORTCHARA, PICKUPCHARA, ADDCOPYCHARA,
    NOBLANK, NODISP, ALIGNMENT,
    FONTSTYLE, SETFONT,
    DRAWLINE, CLEARLINE,
    OUTPUT_ENCODED, REPLACE,

    // 추가 명령어
    BREAK, CONTINUE,
    INPUTS,
    PRINTDATA, PRINTDATAL, PRINTDATAW,
    DATALIST, DATAFORM, ENDDATA, ENDLIST,
    CATCH, ENDCATCH,
    SWAP, TIMES,
    SETBIT, CLEARBIT, INVERTBIT, GETBIT,
    FINDCHARA, GETCHARA, ADDDEFCHARA, ISASSI,
    GETPALAMLV, GETEXPLV, UPCHECK,
    RESETDATA, RESTART,
    REDRAW, REUSELASTLINE, PUTFORM,
    CUSTOMDRAWLINE, BAR,
    SHUFFLE, SPLIT_CMD,
    STRLENFORM, STRLENSU, SUBSTRINGU,
    GETFONT, CHKFONT,
    FONTBOLD, FONTITALIC, FONTREGULAR,
    JUMP, JUMPFORM, TRYJUMP, TRYCCALL, TRYCCALLFORM,
    CALLEVENT,
    UNICODE,

    // Operators
    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO, POWER,
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MODULO_ASSIGN,
    INCREMENT, DECREMENT,
    EQ, NEQ, LT, LTE, GT, GTE,
    AND, OR, NOT, BITAND, BITOR, BITXOR, BITNOT,
    LSHIFT, RSHIFT,
    TERNARY_IF, TERNARY_ELSE,

    // Delimiters
    LPAREN, RPAREN, LBRACKET, RBRACKET,
    COMMA, COLON, SEMICOLON, AT,
    NEWLINE, EOF,

    // Special
    LABEL, FUNCTION_LABEL, EVENT_LABEL,
    SHARP_DEFINE, SHARP_DIM, SHARP_DIMS, SHARP_CONST, SHARP_LOCALSIZE, SHARP_LOCALSSIZE,
    SHARP_FUNCTION, SHARP_SINGLE, SHARP_LATER, SHARP_ONLY, SHARP_PRI,
    COMMENT,

    // String formatting
    FORMSTRING_START, FORMSTRING_END, EMBED_START, EMBED_END,
}

data class Token(
    val type: TokenType,
    val value: String,
    val line: Int,
    val column: Int
) {
    override fun toString() = "Token($type, '$value', L$line:C$column)"
}